\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{SBBook}

\LoadClass[a4paper, fleqn, twoside]{book}

% \let\origin@lmaketitle\maketitle
% \def\makebooktitle{
%  \def\@titlehead{\centering\st@logo\\\smallskip\large\st@university}
%  \def\@title{\st@title}
%  \def\@subject{\@fordegree\\\st@subject}
%\def\@edition{\st@edition
%  \def\@author{{\normalsize\@by}\\{\st@author} \\[1.5\bigskipamount]%
%    {\normalsize\@undersup}\\{\itshape\st@supervisor}%
%    \\[1.5\bigskipamount]}
%\def\@date{\ifdefined\st@date\st@date\else\if@Latin\latintoday\else\today\fi\fi}
%  \origin@lmaketitle
%  \newcommand\date[1]{\def\st@date{##1}}
%  \newcommand\title[1]{\def\st@title{##1}}
%  \newcommand\author[1]{\def\st@author{##1}}
%  \newcommand\edition[1]{\def\st@edition{##1}}}

%\renewcommand\date[1]{\def\st@date{#1}}
%\renewcommand\title[1]{\def\st@title{#1}}
%\renewcommand\author[1]{\def\st@author{#1}}
%\renewcommand\edition[1]{\def\st@edition{#1}}
%}